apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: {{MYNAME}}
  namespace: {{MYNS}}
spec:
  topology:
    controlPlane:
      count: 3
      class: best-effort-small
      storageClass: vsansp
    workers:
      count: 5
      class: best-effort-xsmall
      storageClass: vsansp
  distribution:
    version: {{VERSION}}
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
